name: test-run

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  pre-commit-update:
    uses: dmanthing/test/.github/workflows/pre-commit-update.yml@main
    secrets:
      PRIVATE_ACCESS_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
    with:
      python_version: "3.13"
      branch_name: "update/pre-commit-update"
      pull_request_title: "chore(deps): pre-commit-update updates"
      commit_message: "chore(deps): pre-commit-update updates"
      extra_args: "-v"