name: test-run

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  pre-commit-update:
    uses: dmanthing/test/.github/workflows/pre-commit-update.yml@main
    secrets:
      PRIVATE_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      python_version: "3.13"
      branch_name: "update/pre-commit-update"
      pull_request_title: "chore(deps): upgrade pre-commit-hooks"
      commit_message: "chore(deps): upgrade pre-commit-hooks"