name: pre-commit-update

on:
  workflow_call:
    secrets:
      PRIVATE_ACCESS_TOKEN:
        required: true
    inputs:
      python_version:
        description: "Specify a Python version to use"
        required: false
        default: "3.13"
        type: string
      branch_name:
        description: "Specify a branch name to use for the pull request"
        required: false
        default: "update/pre-commit-update"
        type: string
      pull_request_title:
        description: "Specify a title for the pull request"
        required: false
        default: "chore(deps): pre-commit-update updates"
        type: string
      commit_message:
        description: "Specify a commit message for the pull request"
        required: false
        default: "chore(deps): pre-commit-update updates"
        type: string
      extra_args:
        description: "Specify extra arguments for pre-commit-update"
        required: false
        default: ""
        type: string

jobs:
  run:
    permissions:
      contents: write # peter-evans/create-pull-request
      pull-requests: write # peter-evans/create-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - run: pip install pre-commit-update
        shell: bash
      - run: pre-commit-update ${{ inputs.extra_args }}
        shell: bash
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          branch: ${{ inputs.branch_name }}
          title: ${{ inputs.pull_request_title }}
          commit-message: ${{ inputs.commit_message }}